# Generated by Django 5.2.6 on 2025-09-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propperties', models.CharField(blank=True, max_length=255, null=True)),
                ('current_bid', models.CharField(blank=True, max_length=100, null=True)),
                ('web_scraper_order', models.CharField(blank=True, max_length=100, null=True)),
                ('building_size', models.CharField(blank=True, max_length=100, null=True)),
                ('broker_1', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('links_href', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('pagination', models.TextField(blank=True, null=True)),
                ('bid_increment', models.CharField(blank=True, max_length=100, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('web_scraper_start_url', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=100, null=True)),
                ('property_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('propperties_href', models.TextField(blank=True, null=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('broker_3', models.CharField(blank=True, max_length=255, null=True)),
                ('reserve_not_met', models.CharField(blank=True, max_length=100, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('adress2', models.TextField(blank=True, null=True)),
                ('property_links', models.TextField(blank=True, null=True)),
                ('property_links_href', models.TextField(blank=True, null=True)),
                ('year_built', models.CharField(blank=True, max_length=50, null=True)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('starting_bid', models.CharField(blank=True, max_length=100, null=True)),
                ('broker_2', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
